### ISSUE TITLE
Doesn't work on MacOS. SIGILL: illegal instruction

### ISSUE THREAD

**Issue by esuwu** [kilic/bn254#2]
Hi, I tried to run tests of your implementation and they didn't pass. It seems like the problem is about arifmethic.s file. Maybe my CPU is some kind of old. I attached a result of tests here. Can you help with that? Should I, probably, generate arifmethic.s file on my computer?
[message.txt](https://github.com/kilic/bn254/files/5297656/message.txt)

**Comment by kilic** [comment]
https://github.com/kilic/bn254/commit/dd29157ef4fdd35c578a4f3329da5d64dd046dff
